new 
	vehicle_radio_list [ MAX_VEHICLES ] = { -1, ... },
	vehicle_radio_list_station[MAX_VEHICLES][72];
	
new const
	radio_list[ 12 ][ 2 ][ 128 ] = 
	{
		{ "radio_list Los-Santos", "http://g-rp.su/radio_list/lsfm.m3u" },
		{ "Station 48", "http://g-rp.su/radio_list/grind_fm.m3u" },
		{ "Station 69", "http://g-rp.su/radio_list/nonstopplay.m3u" },
		{ "Station 92", "http://g-rp.su/radio_list/record_club_320.m3u" },
		{ "Station 133", "http://g-rp.su/radio_list/defjay.m3u" },
		{ "Station 214", "http://g-rp.su/radio_list/bassdrive.m3u" },
		{ "Station 264", "http://g-rp.su/radio_list/classic.m3u" },
		{ "Station 311", "http://g-rp.su/radio_list/jazz.m3u" },
		{ "Station 367", "http://g-rp.su/radio_list/easylisten.m3u" },
		{ "Station 452", "http://g-rp.su/radio_list/metall.m3u" },
		{ "Station 452", "http://g-rp.su/radio_list/dnb.m3u" },
		{ "Собственная радиостанция", "" }
	};